### ISSUE TITLE
Chart is not working in some cases

### ISSUE THREAD

**Issue by onlinebizsoft** [MonogoPolska/monogo-m2-pagespeed-analysis#2]
We have fixed this and attached is the patch
[patches_composer_0001-6611-Monogo_PagespeedAnalysis-grid-error-js.txt](https://github.com/MonogoPolska/monogo-m2-pagespeed-analysis/files/7115798/patches_composer_0001-6611-Monogo_PagespeedAnalysis-grid-error-js.txt)

**Comment by pawel-detka** [comment]
Hi @onlinebizsoft 
Please check 1.3.3 version. Big thanks!
